packages:
  - !include common_slave.yaml

psram:
  mode: octal
  speed: 80MHz

logger:
  logs:
    interval: NONE
    binary_sensor: NONE

globals:
  - id: liquid1_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid2_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid3_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid4_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid5_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid6_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid7_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid8_last_time
    type: unsigned long
    initial_value: '0'
  - id: liquid1_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid2_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid3_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid4_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid5_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid6_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid7_8_interval
    type: unsigned long
    initial_value: '0'
  - id: liquid_time_threshold
    type: unsigned long
    initial_value: '1000'  # 默认1秒阈值，可调整
wifi:  
  networks:
    - ssid: "Latent Spice"
      password: "bqsj123456"
      priority: 0
    - ssid: "bqsj-nono"
      password: "Qzpm!234.."
      priority: 1
  # fast_connect: true
  power_save_mode: none

ota: 
  - platform: esphome
web_server: 
  port: 80

uart:
  - id: uart_com
    tx_pin: 17
    rx_pin: 18
    baud_rate: 115200
    
  - id: uart_pi
    tx_pin: 19
    rx_pin: 20
    baud_rate: 9600
    debug:
      direction: BOTH
      dummy_receiver: true
      after:
        delimiter: [0xAA]
      sequence:
        - lambda: |-
            UARTDebug::log_string(direction, bytes);
            if (direction == UARTDirection::UART_DIRECTION_RX) {
              if(bytes[0] == 0x0f && bytes[7] == 0xAA) {
                uint8_t module = bytes[2];
                uint16_t data1 = bytes[3] << 8 | bytes[4];
                uint16_t data2 = bytes[5] << 8 | bytes[6];
                if(module == 0 && data1 == 1 && data2 == 1) {
                  id(clean_system_slave).publish_state(true);
                }
                if (module == 0xFF) {
                  id(pi_started_slave).publish_state(true);
                } 
              }
            }

packet_transport:
  - platform: uart
    uart_id: uart_com
    update_interval: 1s
    binary_sensors:
      - tank1_slave
      - tank2_slave
      - tank3_slave
      - tank4_slave
      - tank5_slave
      - tank6_slave
      - tank7_slave
      - tank8_slave
      - liquid1_slave
      - liquid2_slave
      - valve1_slave_sensor
      - valve2_slave_sensor
      - water_pump_slave_sensor
      - clean_system_slave
      - pi_started_slave

switch:
  - platform: gpio
    pin: 4
    id: restart_master
    restore_mode: ALWAYS_ON
    # internal: true

  - platform: gpio
    pin: 5
    name: pump 水泵
    id: water_pump_slave_switch

  - platform: gpio
    pin: 48
    name: 电解模块
    id: o3_en

  - platform: gpio
    pin: 1
    name: 半导体1
    id: ice1
  - platform: gpio
    pin: 2
    name: 半导体2
    id: ice2

  - platform: gpio
    pin: 45
    name: Valve 1
    id: valve1

  - platform: gpio
    pin: 46
    name: Valve 2
    id: valve2

output: 
  - platform: ledc
    id: fridge_fan1_output
    frequency: 5kHz
    pin: 42
  - platform: ledc
    id: fridge_fan2_output
    frequency: 5kHz
    pin: 41
  - platform: ledc
    id: exhaust_fan_output
    frequency: 5kHz
    pin: 40

fan:
  - platform: speed
    output: fridge_fan1_output
    name: 冰箱风扇1
    id: fridge_fan1
  # - platform: speed
  #   output: fridge_fan2_output
  #   name: 冰箱风扇2
  #   id: fridge_fan2
  - platform: speed
    output: exhaust_fan_output
    name: 散热风扇
    id: exhaust_fan


light:
  - platform: esp32_rmt_led_strip
    id: led_rgb2
    name: "底座LED"
    # chipset: WS2811
    rgb_order: RGB
    pin: 15 
    num_leds: 30
    use_psram: false
    rmt_symbols: 96
    bit0_high: 300ns
    bit1_high: 790ns
    bit0_low: 790ns
    bit1_low: 790ns
    reset_low: 320us
    on_turn_on:
      - light.turn_on:  
          id: led_rgb2
          red: 0.598
          green: 0.688
          blue: 1.0
          brightness: 1.0
    

binary_sensor:
  - platform: template
    id: water_pump_slave_sensor
    lambda: |-
      return id(water_pump_slave_switch).state;
    on_press:
      - switch.turn_on: water_pump_slave_switch
    on_release:
      - switch.turn_off: water_pump_slave_switch

  - platform: template
    id: valve1_slave_sensor
    lambda: |-
      return id(valve1).state;
    on_press:
      - switch.turn_on: valve1
    on_release:
      - switch.turn_off: valve1

  - platform: template
    id: valve2_slave_sensor
    lambda: |-
      return id(valve2).state;
    on_press:
      - switch.turn_on: valve2
    on_release:
      - switch.turn_off: valve2

  # 接收主机控制命令
  - platform: packet_transport
    provider: baros
    remote_id: valve1_control
    id: valve1_control_receive
    internal: true
    on_press:
      - switch.turn_on: valve1
    on_release:
      - switch.turn_off: valve1

  - platform: packet_transport
    provider: baros
    remote_id: valve2_control
    id: valve2_control_receive
    internal: true
    on_press:
      - switch.turn_on: valve2
    on_release:
      - switch.turn_off: valve2

  - platform: packet_transport
    provider: baros
    remote_id: water_pump_control
    id: water_pump_control_receive
    internal: true
    on_press:
      - switch.turn_on: water_pump_slave_switch
    on_release:
      - switch.turn_off: water_pump_slave_switch

  - platform: packet_transport
    provider: baros
    remote_id: o3_control
    id: o3_control_receive
    internal: true
    on_press:
      - switch.turn_on: o3_en
    on_release:
      - switch.turn_off: o3_en

  - platform: gpio
    pin: 
      number: 12
      inverted: true
    name: Tank4
    id: tank4_slave
    internal: false
    filters:
      - delayed_on: 900ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 4
            data2: !lambda "return x;"
    
  - platform: gpio
    pin: 
      number: 11
      inverted: true
    name: Tank3
    id: tank3_slave
    internal: false
    filters:
      - delayed_on: 900ms
      - delayed_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 3
            data2: !lambda "return x;"

  - platform: gpio
    pin: 
      number: 10
      inverted: true
    name: Tank2
    id: tank2_slave
    internal: false
    filters:
      - delayed_on: 900ms
      - delayed_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 2
            data2: !lambda "return x;"

  - platform: gpio
    pin: 
      number: 9
      inverted: true
    name: Tank1
    id: tank1_slave
    internal: false
    filters:
      - delayed_on: 900ms
      - delayed_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 1
            data2: !lambda "return x;"
    
  - platform: gpio
    pin: 
      number: 13
      inverted: true
    name: Tank5
    id: tank5_slave
    internal: false
    filters:
      - delayed_on: 900ms
      - delayed_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 5
            data2: !lambda "return x;"

  - platform: gpio
    pin: 
      number: 14
      inverted: true
    name: Tank6
    id: tank6_slave
    internal: false
    filters:
      - delayed_on: 900ms
      - delayed_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 6
            data2: !lambda "return x;"

  - platform: gpio
    pin: 
      number: 21
      inverted: true
    name: Tank7
    id: tank7_slave
    internal: false
    filters:
      - delayed_on: 900ms 
      - delayed_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 7
            data2: !lambda "return x;"

  - platform: gpio
    pin: 
      number: 47
      inverted: true
    name: Tank8
    id: tank8_slave
    internal: false
    filters:
      - delayed_on: 900ms
      - delayed_off: 100ms
    on_state:
      then:
        - script.execute:
            id: send_to_pi
            module: 1
            data1: 8
            data2: !lambda "return x;"

  - platform: gpio
    pin:
      number: 39
      mode:
        input: true
        pulldown: true
      inverted: true
    name: Liquid1
    id: liquid1_slave
    internal: false
    filters:
      - delayed_on: 900ms
      - delayed_off: 100ms
    on_press:
      then:
        - lambda: |-
            auto now = millis();
            id(liquid1_last_time) = now;
            ESP_LOGI("liquid1", "Liquid1 开启，记录时间: %lu ms", now);
        - logger.log:
            format: " Liquid1 状态变化: 开启"
            level: INFO
    on_release:
      then:
        - logger.log:
            format: " Liquid1 状态变化: 关闭"
            level: INFO
  - platform: gpio
    pin:
      number: 38
      mode:
        input: true
        pulldown: true
      inverted: true
    name: Liquid2
    id: liquid2_slave
    internal: false
    filters:
      - delayed_on: 900ms
      - delayed_off: 100ms
    on_press:
      then:
        - lambda: |-
            auto now = millis();
            id(liquid2_last_time) = now;
            ESP_LOGI("liquid2", "Liquid2 开启，记录时间: %lu ms", now);
        - logger.log:
            format: " Liquid2 状态变化: 开启"
            level: INFO
    on_release:
      then:
        - logger.log:
            format: " Liquid2 状态变化: 关闭"
            level: INFO

script:
button:
  - platform: template
    name: 重启主MCU
    on_press:
      - then:
          - switch.turn_off: restart_master
          - delay: 0.5s
          - switch.turn_on: restart_master


