globals:
  - id: SERVER_STATUS
    type: bool
    initial_value: 'false'

  - id: WIFI_STATUS
    type: bool
    initial_value: 'false'

ota: 
  - platform: esphome
  - platform: web_server
  - platform: http_request


wifi:  
  networks:
    - ssid: "Latent Spice"
      password: "bqsj123456"
      priority: 0
    - ssid: "bqsj-nono"
      password: "Qzpm!234.."
      priority: 1
  power_save_mode: none
  on_connect:
    - globals.set:
        id: WIFI_STATUS
        value: "true"
  on_disconnect:
    - globals.set:
        id: WIFI_STATUS
        value: "false"
web_server: 
  port: 80
  version: 3
  local: true
  sorting_groups:


binary_sensor:
  # 网络状态传感器
  - platform: template
    name: Wifi Status
    id: wifi_status_main
    lambda: !lambda 'return id(WIFI_STATUS);'

  - platform: template
    name: Server Status
    id: server_status_main
    lambda: !lambda 'return id(SERVER_STATUS);'




  # 通知辅MCU 告诉树莓派出酒状态
  - platform: template
    name: Recipe Running
    id: pouring
    condition:
      for:
        time: 1s
        condition:
          lambda: |-
            if(id(LIQUID_POURING)){
              return true;
            } else {
              return false;
            }
  - platform: packet_transport
    provider: baros-slave
    remote_id: clean_system_slave
    id: clean_system_sensor
    name: Clean System
    internal: false
    on_press:
      then:
        - script.execute: clean_system


  # 水箱状态传感器 (8个水箱，带自动状态通知)
  - platform: packet_transport
    provider: baros-slave
    remote_id: tank1_slave
    id: tank1
    name: Tank1
    internal: false
  - platform: packet_transport
    provider: baros-slave
    remote_id: tank2_slave
    id: tank2
    name: Tank2
    internal: false

  - platform: packet_transport
    provider: baros-slave
    remote_id: tank3_slave
    id: tank3
    name: Tank3 
    internal: false

  - platform: packet_transport
    provider: baros-slave
    remote_id: tank4_slave
    id: tank4
    name: Tank4
    internal: false

  - platform: packet_transport
    provider: baros-slave
    remote_id: tank5_slave
    id: tank5
    name: Tank5
    internal: false

  - platform: packet_transport
    provider: baros-slave
    remote_id: tank6_slave
    id: tank6
    name: Tank6
    internal: false

  - platform: packet_transport
    provider: baros-slave
    remote_id: tank7_slave
    id: tank7
    name: Tank7
    internal: false

  - platform: packet_transport
    provider: baros-slave
    remote_id: tank8_slave
    id: tank8
    name: Tank8
    internal: false

  # 液位状态传感器 (7个液位传感器)
  - platform: packet_transport
    provider: baros-slave
    remote_id: liquid1_slave
    id: liquid1
    name: Liquid1
    internal: false
  - platform: packet_transport
    provider: baros-slave
    remote_id: liquid2_slave
    id: liquid2
    name: Liquid2
    internal: false



interval:
  - interval: 6s
    then:
      - if:
          condition:
            or:
              - script.is_running: make_recipe
              - script.is_running: pour_liquid
              - switch.is_on: STOP_POST
          then:
            - logger.log: "配方或倒酒正在执行中，跳过定时获取;"
          else: 
            - script.execute: get_recipe
            - script.wait: get_recipe
            - script.execute: make_recipe
            - script.wait: make_recipe

script: 
  # 打印并执行缓存步骤
  - id: make_recipe
    mode: single
    then:
      - if:
          condition:
            lambda: 'return id(RECIPE_READY) == true;'
          then:
            - repeat:
                count: !lambda "return sizeof(id(RECIPE_TANK_ORDER)) / sizeof(id(RECIPE_TANK_ORDER)[0]);"
                then:
                  - if: 
                      condition:
                        lambda: 'return id(RECIPE_TANK_ORDER)[iteration] > 0;'
                      then:
                        - logger.log:
                            format: "执行水箱: %d , 体积: %.1f"
                            args: [ 'id(RECIPE_TANK_ORDER)[iteration]', 'id(RECIPE_WINE_VOLUME)[iteration]' ]
                        - script.execute: 
                            id: pour_liquid
                            tank_num: !lambda "return id(RECIPE_TANK_ORDER)[iteration];"
                            volume: !lambda "return id(RECIPE_WINE_VOLUME)[iteration];"
                        - delay: 1s
            - wait_until:
                for:
                  time: 2s
                  condition:
                    lambda: 'return id(LIQUID_POURING) == false;'
            - lambda: |-
                id(RECIPE_READY) = false;
